name: Riceleaf
channels:
  - conda-forge
  - defaults
dependencies:
  - asgiref=3.8.1=py312haa95532_0
  - beautifulsoup4=4.14.2=pyha770c72_0
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.10.5=h4c7d964_0
  - django=5.2=py312haa95532_0
  - expat=2.7.1=h8ddb27b_0
  - html5lib=1.1=pyhd8ed1ab_2
  - libexpat=2.7.1=hac47afa_0
  - libffi=3.4.4=hd77b12b_1
  - libiconv=1.18=hc1393d2_2
  - libsqlite=3.51.0=hf5d6505_0
  - libxml2=2.13.9=h741aa76_0
  - libxslt=1.1.43=h25c3957_0
  - libzlib=1.3.1=h02ab6af_0
  - lxml=6.0.2=py312hc85b015_0
  - openssl=3.5.4=h725018a_0
  - pip=25.2=pyhc872135_0
  - python=3.12.7=hce54a09_0_cpython
  - python_abi=3.12=8_cp312
  - setuptools=78.1.1=py312haa95532_0
  - six=1.17.0=pyhe01879c_1
  - soupsieve=2.8=pyhd8ed1ab_0
  - sqlite=3.50.2=hda9a48d_1
  - sqlparse=0.5.2=py312haa95532_0
  - tk=8.6.15=hf199647_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - webencodings=0.5.1=pyhd8ed1ab_3
  - wheel=0.45.1=py312haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - attrs==25.4.0
      - certifi==2025.10.5
      - cffi==2.0.0
      - charset-normalizer==3.4.3
      - contourpy==1.3.3
      - cycler==0.12.1
      - django-crontab==0.7.1
      - django-redis==6.0.0
      - filelock==3.19.1
      - fonttools==4.60.1
      - fsspec==2025.9.0
      - h11==0.16.0
      - idna==3.10
      - jinja2==3.1.6
      - kiwisolver==1.4.9
      - markupsafe==3.0.3
      - matplotlib==3.10.6
      - mpmath==1.3.0
      - mysqlclient==2.2.7
      - networkx==3.5
      - numpy==2.2.6
      - opencv-python==4.12.0.88
      - outcome==1.3.0.post0
      - packaging==25.0
      - pandas==2.3.3
      - pillow==11.3.0
      - polars==1.34.0
      - polars-runtime-32==1.34.0
      - psutil==7.1.0
      - pycparser==2.23
      - pyparsing==3.2.5
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - redis==6.4.0
      - requests==2.32.5
      - scipy==1.16.2
      - selenium==4.36.0
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - sympy==1.14.0
      - torch==2.8.0
      - torchvision==0.23.0
      - trio==0.31.0
      - trio-websocket==0.12.2
      - tzdata==2025.2
      - ultralytics==8.3.206
      - ultralytics-thop==2.0.17
      - urllib3==2.5.0
      - websocket-client==1.8.0
      - wsproto==1.2.0
prefix: C:\Users\Mizuyu\.conda\envs\myenv
